[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "src/main.rs"
name = "zero2prod"

[lib]
path = "src/lib.rs"

[dependencies]
actix-web = "4.3.1"
reqwest = "0.11.18"
serde = { version = "1.0.163", features = ["derive"]}
tokio = { version = "1.28.1", features = ["macros", "rt-multi-thread"] }
